#!/usr/bin/env bash
# Rebuilds app/apps/paseo/vendor/paseo-transport.js from the Paseo fork's
# built packages (relay E2EE channel + WebSocket transport adapters) so the
# Faceclaw bundle needs no @getpaseo/* npm dependency. Run after
# `npm run build` in the Paseo repo. The full SDK is not vendored: its
# protocol package pulls ~13 MB of zod schemas into the worker.
set -euo pipefail
repo="${PASEO_REPO:-$HOME/Documents/Personal/paseo-glance}"
out="$(cd "$(dirname "$0")/.." && pwd)/app/apps/paseo/vendor/paseo-transport.js"
client="$repo/packages/client/dist"
[ -f "$client/daemon-client-relay-e2ee-transport.js" ] || { echo "build the Paseo client first: $client" >&2; exit 1; }
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
cat > "$tmp/entry.js" <<ENTRY
export { createEncryptedTransport } from "$client/daemon-client-relay-e2ee-transport.js";
export { createWebSocketTransportFactory } from "$client/daemon-client-websocket-transport.js";
ENTRY
echo "export default {};" > "$tmp/empty.js"
"$repo/node_modules/.bin/esbuild" "$tmp/entry.js" --bundle --format=esm --platform=neutral \
  --main-fields=module,main --conditions=import,default --alias:crypto="$tmp/empty.js" \
  --outfile="$tmp/bundle.js" --log-level=warning
# Faceclaw's OkHttp socket wrapper delivers text frames only, so the E2EE hello
# must not offer binary ciphertext (the daemon would then send binary frames).
count=$(grep -cE '^ *capabilities: \{ binaryCiphertext: true \}$' "$tmp/bundle.js" || true)
[ "$count" = "1" ] || { echo "expected exactly one client hello capability line, found $count" >&2; exit 1; }
sed -i '' -E 's/^( *)capabilities: \{ binaryCiphertext: true \}$/\1capabilities: {}/' "$tmp/bundle.js"
version=$(node -p "require('$repo/packages/client/package.json').version")
{
  echo "// Generated by scripts/refresh-paseo-vendor.sh from @getpaseo/client $version (commit $(git -C "$repo" rev-parse --short HEAD)). Do not edit."
  cat "$tmp/bundle.js"
} > "$out"
echo "wrote $out ($(wc -c < "$out") bytes)"
